# Generated by Django 5.1.1 on 2024-09-30 09:39

import myadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='profile_image',
            field=models.FileField(upload_to='profile_images/', validators=[myadmin.models.validate_image_or_svg]),
        ),
    ]
