# Generated by Django 5.1.1 on 2024-09-30 10:29

import myadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='about_me_image',
            field=models.FileField(blank=True, null=True, upload_to='about_me_images/', validators=[myadmin.models.validate_image_or_svg]),
        ),
    ]
