# Generated by Django 5.1.1 on 2024-09-30 13:30

import myadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_remove_mywork_project_img_mywork_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywork',
            name='project_image',
        ),
        migrations.AddField(
            model_name='mywork',
            name='project_imagee',
            field=models.FileField(null=True, upload_to='projects/', validators=[myadmin.models.validate_image_or_svg]),
        ),
    ]
