# Generated by Django 5.1.1 on 2024-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_remove_mywork_project_image_mywork_project_imagee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_para', models.TextField(verbose_name='Contact Paragraph')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
